import type { FrictionPoint } from "./types";

/** Seed data representing realistic friction points for the dashboard */
export const seedFrictionPoints: FrictionPoint[] = [
  {
    id: "fp-001",
    title: "Checkout flow drops on payment step",
    description:
      "Users abandon the checkout at the payment information step. Form validation errors are unclear and the back button loses cart state.",
    category: "ux",
    severity: "critical",
    status: "investigating",
    reportCount: 342,
    firstReported: "2025-11-02",
    lastReported: "2026-01-28",
    tags: ["checkout", "payment", "conversion"],
  },
  {
    id: "fp-002",
    title: "Dashboard initial load exceeds 4 seconds",
    description:
      "The main dashboard takes over 4 seconds to render on first visit due to blocking API calls and unoptimized bundle size.",
    category: "performance",
    severity: "high",
    status: "open",
    reportCount: 189,
    firstReported: "2025-12-10",
    lastReported: "2026-01-27",
    tags: ["performance", "load-time", "bundle"],
  },
  {
    id: "fp-003",
    title: "Intermittent 502 errors on search API",
    description:
      "The /api/search endpoint returns 502 errors roughly 3% of the time during peak hours, causing empty result states for users.",
    category: "reliability",
    severity: "high",
    status: "investigating",
    reportCount: 127,
    firstReported: "2026-01-05",
    lastReported: "2026-01-28",
    tags: ["api", "search", "502"],
  },
  {
    id: "fp-004",
    title: "New user onboarding wizard skips step 3",
    description:
      "When users navigate back from step 4, the wizard skips step 3 entirely and returns to step 2, losing entered data.",
    category: "onboarding",
    severity: "medium",
    status: "open",
    reportCount: 85,
    firstReported: "2026-01-12",
    lastReported: "2026-01-26",
    tags: ["onboarding", "wizard", "navigation"],
  },
  {
    id: "fp-005",
    title: "Screen reader cannot parse data tables",
    description:
      "Data tables in the reports section lack proper ARIA labels and role attributes, making them unusable for screen reader users.",
    category: "accessibility",
    severity: "high",
    status: "open",
    reportCount: 34,
    firstReported: "2025-12-20",
    lastReported: "2026-01-25",
    tags: ["a11y", "tables", "screen-reader"],
  },
  {
    id: "fp-006",
    title: "Mobile hamburger menu unresponsive on iOS Safari",
    description:
      "The hamburger menu button does not respond to taps on iOS Safari 17.x. Users must refresh the page to get it working.",
    category: "ux",
    severity: "medium",
    status: "open",
    reportCount: 76,
    firstReported: "2026-01-08",
    lastReported: "2026-01-27",
    tags: ["mobile", "ios", "navigation"],
  },
  {
    id: "fp-007",
    title: "Image uploads timeout on slow connections",
    description:
      "File uploads greater than 2 MB timeout after 30 seconds on slower connections with no retry mechanism or progress feedback.",
    category: "reliability",
    severity: "medium",
    status: "investigating",
    reportCount: 63,
    firstReported: "2025-12-15",
    lastReported: "2026-01-24",
    tags: ["upload", "timeout", "reliability"],
  },
  {
    id: "fp-008",
    title: "Color contrast fails WCAG AA on sidebar links",
    description:
      "Sidebar navigation links use #999 on #f5f5f5 background, which fails WCAG AA contrast requirements (ratio 2.8:1).",
    category: "accessibility",
    severity: "low",
    status: "open",
    reportCount: 12,
    firstReported: "2026-01-15",
    lastReported: "2026-01-22",
    tags: ["a11y", "contrast", "sidebar"],
  },
  {
    id: "fp-009",
    title: "Password reset email delayed by 10+ minutes",
    description:
      "Password reset emails are delayed significantly during business hours due to email queue congestion, causing users to retry and flood the queue further.",
    category: "reliability",
    severity: "high",
    status: "resolved",
    reportCount: 201,
    firstReported: "2025-11-20",
    lastReported: "2026-01-15",
    tags: ["auth", "email", "queue"],
  },
  {
    id: "fp-010",
    title: "Tooltip text overlaps on narrow viewports",
    description:
      "Help tooltips on the settings page overflow their containers on viewports narrower than 768px, rendering text unreadable.",
    category: "ux",
    severity: "low",
    status: "resolved",
    reportCount: 28,
    firstReported: "2025-12-28",
    lastReported: "2026-01-10",
    tags: ["responsive", "tooltip", "settings"],
  },
  {
    id: "fp-011",
    title: "API rate limiting returns wrong status code",
    description:
      "When rate limited, the API returns 500 instead of 429, causing client retry logic to loop instead of backing off.",
    category: "reliability",
    severity: "critical",
    status: "resolved",
    reportCount: 156,
    firstReported: "2025-12-01",
    lastReported: "2026-01-08",
    tags: ["api", "rate-limit", "status-code"],
  },
  {
    id: "fp-012",
    title: "Onboarding video fails to load in EU regions",
    description:
      "The onboarding tutorial video is hosted on a US-only CDN, causing it to fail loading for EU-based users with a blank player.",
    category: "onboarding",
    severity: "medium",
    status: "resolved",
    reportCount: 91,
    firstReported: "2025-12-05",
    lastReported: "2026-01-03",
    tags: ["onboarding", "video", "cdn", "geo"],
  },
];
